### ISSUE TITLE
Bonus hearts disappear or reset after a while in game

### ISSUE THREAD

**Issue by Joccob** [SilentChaos512/ScalingHealth#188]
### Versions

- **Scaling Health**: ScalingHealth-1.12.2-1.3.40+145
- **Silent Lib**: SilentLib-1.12.2-3.0.13+167
- **Forge**: forge-14.23.5.2838
- **Modpack** (if applicable): Custom

### Expected behavior
The bonus health I get from the mod will disappear randomly without crushing the game.

- Sometimes I still have the actual amount of health but the health bar only render vanilla 20 health. And sometimes the health is completely gone.

### Actual behavior
This happens after I transfer the save from my server to my PC. I switched a few mods and play as a singleplayer save now. Every time I fully log out and log back in (close the game or load other maps), my health bar will reset to vanilla 20 health bar with 10 heart. But that's not the end. I use the command to give the heart back and after a while, it just suddenly disappear again while I'm playing. As I mentioned before, sometimes I still have the actual amount of health but the health bar only render vanilla 20 health. I find out this by losing some health and the actual health bar will glitch back on for a very short period when recovering. And sometimes the health is completely gone. 

- It does not always happen the minute I login, but within 10-30min of playing, it will happen
- I try to delete the config and reinstall the mod, but it didn't work
- Since it will happen multiple times while I'm playing, I feel like their mush be some conflictions with other mods. However, I couldn't find which one is causing this problem

### Links/Images
Modlist is attached down below

- https://pastebin.com/bxaQdqJY

### Steps to reproduce the problem

1. Get extra heart in game and log out
2. Close the game or load other maps before log back in
3. Load the save and play for a while, the health bar will suddenly change back to vanilla health bar.

**Comment by SkyeMors** [comment]
Confirmed, had the same issue with bonus health either not rendering or not existing after a re-log.
Thankfully I'm still early-game (fresh re-installation), so it's not critical- but annoying nonetheless.

I vaguely remember a similar issue for the 1.12.2 version about a year ago, which was fixed by messing with the minimum/maximum health settings, I don't recall.

**Comment by Joccob** [comment]
Thanks for the info, I'll try to adjust the minimum/maximum health settings to see if it works. But what really confuses me is that I play this pack for quite long with my friends on the server and this problem never exists...

**Comment by DainXOR** [comment]
> I vaguely remember a similar issue for the 1.12.2 version about a year ago, which was fixed by messing with the minimum/maximum health settings, I don't recall.

I'm having the same issue, i did changed a bit the config file but it still happends.

Scaling Health: ScalingHealth-1.12.2-1.3.42+147
Silent Lib: SilentLib-1.12.2-3.0.13+167

**Comment by n-wach** [comment]
Apologies as this is unrelated to the issue and repo, but Google brought me here, and it may bring others... 

I am playing GregTech: New Horizons. After getting the Healing Axe, my bonus hearts started to go away. 

Turns out it was because my nutrition levels were falling below 90% (each category above 90% gives 2 bonus hearts). The Healing Axe only brings each level to 50%. [link](https://www.reddit.com/r/GTNH/comments/1ip7mi9/i_lost_4_of_my_permanent_hearts_not_sure_how_of/)

**Comment by SkyeMors** [comment]
> Apologies as this is unrelated to the issue and repo, but Google brought me here, and it may bring others...

...that is possibly the dumbest reason ever. Google Search has been bad for a decade now, and for some reason you think it was a good idea to post on an unrelated github page, about an unrelated mod, about an unrelated bug... about a feature of a modpack that only shares that it's Minecraft, and has anything to do with Health.

Might as well post to EVERY bug page on EVERY github bug report, just in case someone goes there, too. /s

Just find where the modpack is hosted, look for a bug reports section, and file a bug report if it is one- otherwise wtf are you doing, besides necroposting?
